---
generic-service:
  nameOverride: hmpps-approved-premises-api

  replicaCount: 4

  livenessProbe:
    initialDelaySeconds: 60

  image:
    repository: quay.io/hmpps/hmpps-approved-premises-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-approved-premises-api-cert
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
    SPRING_JPA_DATABASE: postgresql
    SPRING_DATASOURCE_URL: "jdbc:postgresql://${DB_HOST}/${DB_NAME}"
    SPRING_DATA_REDIS_PORT: 6379
    SPRING_DATA_REDIS_SSL_ENABLED: true
    SENTRY_SAMPLE-RATE: 1
    SENTRY_TRACES-SAMPLE-RATE: 0.01
    HMPPS_SQS_PROVIDER: "aws"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-approved-premises-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DELIUS-BACKED-APIS_CLIENT-ID: "SYSTEM_CLIENT_DELIUS_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DELIUS-BACKED-APIS_CLIENT-SECRET: "SYSTEM_CLIENT_DELIUS_SECRET"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_HMPPS-TIER_CLIENT-ID: "SYSTEM_CLIENT_TIER_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_HMPPS-TIER_CLIENT-SECRET: "SYSTEM_CLIENT_TIER_SECRET"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PRISONS-API_CLIENT-ID: "SYSTEM_CLIENT_NOMIS_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PRISONS-API_CLIENT-SECRET: "SYSTEM_CLIENT_NOMIS_SECRET"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PRISONER-ALERTS-API_CLIENT-ID: "SYSTEM_CLIENT_NOMIS_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PRISONER-ALERTS-API_CLIENT-SECRET: "SYSTEM_CLIENT_NOMIS_SECRET"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOMIS-USER-ROLES-API_CLIENT-ID: "SYSTEM_CLIENT_NOMIS_USER_ROLES_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CASE-NOTES_CLIENT-ID: "SYSTEM_CLIENT_OFFENDER_CASE_NOTES_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CASE-NOTES_CLIENT-SECRET: "SYSTEM_CLIENT_OFFENDER_CASE_NOTES_SECRET"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AP-OASYS-CONTEXT_CLIENT-ID: "SYSTEM_CLIENT_APPROVED_PREMISES_AND_OASYS_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AP-OASYS-CONTEXT_CLIENT-SECRET: "SYSTEM_CLIENT_APPROVED_PREMISES_AND_OASYS_SECRET"
      SENTRY_DSN: "SENTRY_DSN"
    rds-postgresql-instance-output:
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
      DB_HOST: "rds_instance_endpoint"
      DB_NAME: "database_name"
    elasticache-redis:
      SPRING_DATA_REDIS_HOST: "primary_endpoint_address"
      SPRING_DATA_REDIS_PASSWORD: "auth_token"
    cas-2-domain-events-queue:
      HMPPS_SQS_QUEUES_CASTWODOMAINEVENTSQUEUE_QUEUE_NAME: "QUEUE_NAME"
    cas-2-domain-events-dlq:
      HMPPS_SQS_QUEUES_CASTWODOMAINEVENTSDLQ_DLQ_NAME: "QUEUE_NAME"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: hmpps-approved-premises-api
