name: Security OWASP dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "51 3 * * MON-FRI" # Every weekday at 03:51 UTC
jobs:
  security-kotlin-owasp-check:
    name: Kotlin security OWASP dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_owasp.yml@v2 # WORKFLOW_VERSION
    with:
      nvd_feed_version: '2'
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      nvd_feed_version: '2'
    secrets: inherit
